### ISSUE TITLE
Does not compile on 4.4.0-75

### ISSUE THREAD

**Issue by CaledoniaProject** [nbulischeck/tyton#17]
Can't compile master branch on Ubuntu 16.04 + kernel 4.4.0-75, can you take a look?

```
/tmp/tyton-master/src/network_hooks.c: In function 'analyze_networks':
/tmp/tyton-master/src/network_hooks.c:54:42: error: dereferencing pointer to incomplete type 'const struct file_operations'
   op_addr[0] = *(unsigned long *)seq_fops->llseek;
```

**Comment by nbulischeck** [comment]
@CaledoniaProject That error refers to when you try to use a struct with no reference to its declaration in the code.

Looking at the source tree for v4.4, `struct file_operations` (which is what seq_fops is defined as) definitely exists - https://elixir.bootlin.com/linux/v4.4/source/include/linux/fs.h#L1600

One solution I could see is prepending `#include <linux/fs.h>` in the header of `network_hooks.h` to make sure that it gets included.

For testing purposes can you add `#include <linux/fs.h>` to the top of `src/network_hooks.c` and try to build it again?

**Comment by CaledoniaProject** [comment]
Sure :-)
